/**
 * Demo data for school portal testing
 * This provides realistic sample data for unauthenticated users to explore the platform
 */

export const demoSchools = [
  {
    id: "demo-ueh",
    name: "Université d'État d'Haïti (UEH)",
    slug: "ueh",
    city: "Port-au-Prince",
    country: "Haiti",
    description: "Haiti's premier public university, founded in 1920, offering comprehensive programs in sciences, humanities, and professional studies.",
    contactEmail: "admissions@ueh.edu.ht",
    contactPhone: "+509 2222 5555",
    websiteUrl: "https://www.ueh.edu.ht",
    logo: "/schools/ueh-logo.png",
  },
  {
    id: "demo-uniq",
    name: "Université Quisqueya (UniQ)",
    slug: "uniq",
    city: "Port-au-Prince",
    country: "Haiti",
    description: "Private institution established in 1988, known for excellence in business, engineering, and health sciences.",
    contactEmail: "info@uniq.edu.ht",
    contactPhone: "+509 2222 0200",
    websiteUrl: "https://www.uniq.edu.ht",
    logo: "/schools/uniq-logo.png",
  },
  {
    id: "demo-uneph",
    name: "Université Episcopale d'Haïti (UNEPH)",
    slug: "uneph",
    city: "Port-au-Prince",
    country: "Haiti",
    description: "Episcopal university offering programs in theology, education, social sciences, and community development.",
    contactEmail: "admissions@uneph.edu.ht",
    contactPhone: "+509 2245 1912",
    websiteUrl: "https://www.uneph.edu.ht",
    logo: "/schools/uneph-logo.png",
  },
  {
    id: "demo-uninotre-dame",
    name: "Université Notre Dame d'Haïti (UNDH)",
    slug: "undh",
    city: "Port-au-Prince",
    country: "Haiti",
    description: "Catholic university focused on holistic education with programs in liberal arts, sciences, and professional studies.",
    contactEmail: "contact@undh.edu.ht",
    contactPhone: "+509 2813 5000",
    websiteUrl: "https://www.undh.edu.ht",
    logo: "/schools/undh-logo.png",
  },
];

export const demoPrograms = [
  // UEH Programs
  {
    id: "prog-ueh-1",
    universityId: "demo-ueh",
    universityName: "Université d'État d'Haïti",
    name: "Licence en Informatique",
    degree: "Bachelor",
    description: "Bachelor's degree in Computer Science covering programming, algorithms, databases, and software engineering.",
    requirements: "Baccalauréat Part I & II, Mathematics proficiency, Basic computer skills",
    feeCents: 25000, // 250 HTG
    currency: "HTG",
    deadline: "2025-12-31",
    duration: "4 years",
    language: "French/Creole",
    isActive: true,
  },
  {
    id: "prog-ueh-2",
    universityId: "demo-ueh",
    universityName: "Université d'État d'Haïti",
    name: "Licence en Administration des Affaires",
    degree: "Bachelor",
    description: "Business Administration degree focusing on management, finance, marketing, and entrepreneurship.",
    requirements: "Baccalauréat Part I & II, Economics or Business background preferred",
    feeCents: 22500,
    currency: "HTG",
    deadline: "2025-12-31",
    duration: "4 years",
    language: "French/Creole",
    isActive: true,
  },
  {
    id: "prog-ueh-3",
    universityId: "demo-ueh",
    universityName: "Université d'État d'Haïti",
    name: "Licence en Génie Civil",
    degree: "Bachelor",
    description: "Civil Engineering program covering structural design, construction management, and infrastructure development.",
    requirements: "Baccalauréat Part I & II (Sciences), Strong mathematics and physics background",
    feeCents: 30000,
    currency: "HTG",
    deadline: "2025-12-31",
    duration: "5 years",
    language: "French",
    isActive: true,
  },
  {
    id: "prog-ueh-4",
    universityId: "demo-ueh",
    universityName: "Université d'État d'Haïti",
    name: "Master en Santé Publique",
    degree: "Master",
    description: "Graduate program in Public Health focusing on epidemiology, health policy, and community health.",
    requirements: "Bachelor's degree in health sciences or related field, 2+ years professional experience",
    feeCents: 45000,
    currency: "HTG",
    deadline: "2025-12-15",
    duration: "2 years",
    language: "French/English",
    isActive: true,
  },

  // UniQ Programs
  {
    id: "prog-uniq-1",
    universityId: "demo-uniq",
    universityName: "Université Quisqueya",
    name: "Licence en Gestion des Entreprises",
    degree: "Bachelor",
    description: "Business Management degree with emphasis on strategic planning, operations, and organizational leadership.",
    requirements: "Baccalauréat Part I & II, Interview required",
    feeCents: 150000,
    currency: "HTG",
    deadline: "2025-12-20",
    duration: "4 years",
    language: "French/English",
    isActive: true,
  },
  {
    id: "prog-uniq-2",
    universityId: "demo-uniq",
    universityName: "Université Quisqueya",
    name: "Licence en Sciences Infirmières",
    degree: "Bachelor",
    description: "Nursing Sciences program preparing students for professional nursing practice and healthcare leadership.",
    requirements: "Baccalauréat Part I & II (Sciences), Health certificate, Interview",
    feeCents: 175000,
    currency: "HTG",
    deadline: "2025-11-30",
    duration: "4 years",
    language: "French",
    isActive: true,
  },
  {
    id: "prog-uniq-3",
    universityId: "demo-uniq",
    universityName: "Université Quisqueya",
    name: "Master en Finance et Comptabilité",
    degree: "Master",
    description: "Advanced degree in Finance and Accounting covering financial analysis, auditing, and corporate finance.",
    requirements: "Bachelor's in Business, Economics, or Accounting, GMAT/GRE recommended",
    feeCents: 250000,
    currency: "HTG",
    deadline: "2025-12-10",
    duration: "2 years",
    language: "French/English",
    isActive: true,
  },
  {
    id: "prog-uniq-4",
    universityId: "demo-uniq",
    universityName: "Université Quisqueya",
    name: "Licence en Génie Électrique",
    degree: "Bachelor",
    description: "Electrical Engineering program focusing on power systems, electronics, and telecommunications.",
    requirements: "Baccalauréat Part I & II (Sciences), Strong math and physics scores",
    feeCents: 180000,
    currency: "HTG",
    deadline: "2025-12-31",
    duration: "5 years",
    language: "French",
    isActive: true,
  },

  // UNEPH Programs
  {
    id: "prog-uneph-1",
    universityId: "demo-uneph",
    universityName: "Université Episcopale d'Haïti",
    name: "Licence en Théologie",
    degree: "Bachelor",
    description: "Theology degree focusing on biblical studies, church history, and pastoral ministry.",
    requirements: "Baccalauréat Part I & II, Letter of recommendation from church leader",
    feeCents: 80000,
    currency: "HTG",
    deadline: "2025-12-15",
    duration: "4 years",
    language: "French/Creole",
    isActive: true,
  },
  {
    id: "prog-uneph-2",
    universityId: "demo-uneph",
    universityName: "Université Episcopale d'Haïti",
    name: "Licence en Travail Social",
    degree: "Bachelor",
    description: "Social Work program preparing students for community development and social services.",
    requirements: "Baccalauréat Part I & II, Community service experience preferred",
    feeCents: 90000,
    currency: "HTG",
    deadline: "2025-12-20",
    duration: "4 years",
    language: "French/Creole",
    isActive: true,
  },
  {
    id: "prog-uneph-3",
    universityId: "demo-uneph",
    universityName: "Université Episcopale d'Haïti",
    name: "Licence en Sciences de l'Éducation",
    degree: "Bachelor",
    description: "Education Sciences degree for future teachers and educational administrators.",
    requirements: "Baccalauréat Part I & II, Interest in teaching",
    feeCents: 85000,
    currency: "HTG",
    deadline: "2025-12-31",
    duration: "4 years",
    language: "French/Creole",
    isActive: true,
  },

  // UNDH Programs
  {
    id: "prog-undh-1",
    universityId: "demo-uninotre-dame",
    universityName: "Université Notre Dame d'Haïti",
    name: "Licence en Droit",
    degree: "Bachelor",
    description: "Law degree covering civil law, criminal law, constitutional law, and legal practice.",
    requirements: "Baccalauréat Part I & II, Strong writing skills, Interview",
    feeCents: 120000,
    currency: "HTG",
    deadline: "2025-12-10",
    duration: "4 years",
    language: "French",
    isActive: true,
  },
  {
    id: "prog-undh-2",
    universityId: "demo-uninotre-dame",
    universityName: "Université Notre Dame d'Haïti",
    name: "Licence en Psychologie",
    degree: "Bachelor",
    description: "Psychology degree exploring human behavior, mental health, and counseling techniques.",
    requirements: "Baccalauréat Part I & II, Interest in human sciences",
    feeCents: 110000,
    currency: "HTG",
    deadline: "2025-12-20",
    duration: "4 years",
    language: "French",
    isActive: true,
  },
  {
    id: "prog-undh-3",
    universityId: "demo-uninotre-dame",
    universityName: "Université Notre Dame d'Haïti",
    name: "Licence en Communication",
    degree: "Bachelor",
    description: "Communication degree covering journalism, media studies, public relations, and digital media.",
    requirements: "Baccalauréat Part I & II, Portfolio or writing samples preferred",
    feeCents: 105000,
    currency: "HTG",
    deadline: "2025-12-31",
    duration: "4 years",
    language: "French/Creole",
    isActive: true,
  },
];

export const demoApplications = [
  {
    id: "app-1",
    applicantName: "Marie Joseph",
    applicantEmail: "marie.joseph@email.com",
    program: "Licence en Informatique",
    universityName: "Université d'État d'Haïti",
    submittedAt: "2025-11-10T14:30:00Z",
    status: "SUBMITTED",
  },
  {
    id: "app-2",
    applicantName: "Jean Baptiste",
    applicantEmail: "jean.baptiste@email.com",
    program: "Licence en Administration des Affaires",
    universityName: "Université d'État d'Haïti",
    submittedAt: "2025-11-09T10:15:00Z",
    status: "UNDER_REVIEW",
  },
  {
    id: "app-3",
    applicantName: "Sophie Laurent",
    applicantEmail: "sophie.laurent@email.com",
    program: "Master en Santé Publique",
    universityName: "Université d'État d'Haïti",
    submittedAt: "2025-11-08T16:45:00Z",
    status: "ACCEPTED",
  },
  {
    id: "app-4",
    applicantName: "Pierre Duval",
    applicantEmail: "pierre.duval@email.com",
    program: "Licence en Gestion des Entreprises",
    universityName: "Université Quisqueya",
    submittedAt: "2025-11-12T09:20:00Z",
    status: "SUBMITTED",
  },
  {
    id: "app-5",
    applicantName: "Claude Michel",
    applicantEmail: "claude.michel@email.com",
    program: "Licence en Sciences Infirmières",
    universityName: "Université Quisqueya",
    submittedAt: "2025-11-11T11:30:00Z",
    status: "UNDER_REVIEW",
  },
  {
    id: "app-6",
    applicantName: "Nadine Alexandre",
    applicantEmail: "nadine.alexandre@email.com",
    program: "Licence en Génie Civil",
    universityName: "Université d'État d'Haïti",
    submittedAt: "2025-11-07T13:00:00Z",
    status: "REJECTED",
  },
  {
    id: "app-7",
    applicantName: "Robert François",
    applicantEmail: "robert.francois@email.com",
    program: "Licence en Droit",
    universityName: "Université Notre Dame d'Haïti",
    submittedAt: "2025-11-13T15:45:00Z",
    status: "SUBMITTED",
  },
  {
    id: "app-8",
    applicantName: "Evelyne Charles",
    applicantEmail: "evelyne.charles@email.com",
    program: "Licence en Psychologie",
    universityName: "Université Notre Dame d'Haïti",
    submittedAt: "2025-11-10T08:30:00Z",
    status: "UNDER_REVIEW",
  },
  {
    id: "app-9",
    applicantName: "Marc Antoine",
    applicantEmail: "marc.antoine@email.com",
    program: "Licence en Travail Social",
    universityName: "Université Episcopale d'Haïti",
    submittedAt: "2025-11-14T12:00:00Z",
    status: "SUBMITTED",
  },
  {
    id: "app-10",
    applicantName: "Lucie Pierre",
    applicantEmail: "lucie.pierre@email.com",
    program: "Master en Finance et Comptabilité",
    universityName: "Université Quisqueya",
    submittedAt: "2025-11-06T14:20:00Z",
    status: "ACCEPTED",
  },
];

export function getDemoSchool(slug?: string) {
  if (slug) {
    return demoSchools.find(s => s.slug === slug) || demoSchools[0];
  }
  return demoSchools[0]; // Default to UEH
}

export function getDemoProgramsByUniversity(universityId: string) {
  return demoPrograms.filter(p => p.universityId === universityId);
}

export function getAllDemoPrograms() {
  return demoPrograms;
}

export function getDemoApplications() {
  return demoApplications;
}
